backend/controller/fetchGenreBooksHandler.go, backend/controller/route.go, backend/model/fetchGenreBooksFunc.go
API to fetch books from DB based on genre given in URL query string. In the above case the request sent is to fetch books tagged with genreid 5.
Sample request : 
http://localhost:8080/api/fetchGenreBooks?id=5
=> API to fetch books from DB based on genre given in URL query string

WebApp/src/app/app-routing.module.ts, WebApp/src/app/app.module.ts, WebApp/src/app/common-menu/common-menu.component.html, WebApp/src/app/common-menu/common-menu.component.ts, WebApp/src/app/genre-books/genre-books.component.html, WebApp/src/app/genre-books/genre-books.component.spec.ts, WebApp/src/app/genre-books/genre-books.component.ts, WebApp/src/app/services/api.service.ts
Created a new component for Genre Description and Book Details
=> GenreBooks Page creation and redirection

WebApp/src/app/app.module.ts, WebApp/src/app/login/login.component.html, WebApp/src/app/login/login.component.scss, WebApp/src/app/login/login.component.ts
Modified Login Page design to include registration UI
=> Login Page Modification

WebApp/cypress.json, WebApp/cypress/.eslintrc.json, WebApp/cypress/fixtures/example.json, WebApp/cypress/integration/login.specs.ts, WebApp/cypress/plugins/index.js, WebApp/cypress/support/commands.js, WebApp/cypress/support/index.js, WebApp/package-lock.json, WebApp/package.json, WebApp/src/app/app.module.ts, WebApp/src/app/login/login.component.html, WebApp/src/app/login/login.component.ts, WebApp/tsconfig.app.json, WebApp/tsconfig.json, WebApp/tsconfig.spec.json
Cypress Setup + Temporary Login Validation from Frontend
=> Frontend login Validation

WebApp/cypress/integration/login.specs.ts, WebApp/src/app/login/login.component.html
Created a Cypress test script to test the Login Feature with possible test cases.
=> Cypress Testing Login Feature

WebApp/src/app/common-menu/common-menu.component.html, WebApp/src/app/common-menu/common-menu.component.ts
Resolved the Hover Issue for Genre Listing
=> Hover Bug Fix

WebApp/cypress/integration/page.spec.ts, WebApp/src/app/common-menu/common-menu.component.html, WebApp/src/app/common-menu/common-menu.component.spec.ts
Did integration testing using Cypress for dynamically clicking genre options and generating genre pages dynamically!
=> Integration testing using Cypress

WebApp/cypress/integration/page.spec.ts
Added a delay between every testcase in the integration testing.
=> Added a delay in Cypress integration testing

WebApp/src/app/common-menu/common-menu.component.html, WebApp/src/app/common-menu/common-menu.component.ts
Logout Feature Implemented to temporarily logout from the application
=> Logout Feature

WebApp/src/app/book-details/book-details.component.html, WebApp/src/app/book-details/book-details.component.scss, WebApp/src/app/book-details/book-details.component.ts, WebApp/src/app/common-menu/common-menu.component.ts, WebApp/src/app/genre-books/genre-books.component.ts, WebApp/src/app/models/general-models.ts, WebApp/src/app/services/api.service.ts
Designed UI for posting a review for a particular book
=> Post Review UI Changes

WebApp/src/app/book-attributes/book-attributes.component.html, WebApp/src/app/book-attributes/book-attributes.component.scss, WebApp/src/app/book-details/book-details.component.html, WebApp/src/app/book-details/book-details.component.scss, WebApp/src/app/book-reviews/book-reviews.component.scss
Author name, publisher name added
=> Added some more attributes to be displayed

WebApp/src/app/book-details/book-details.component.html, WebApp/src/app/book-details/book-details.component.scss, WebApp/src/app/book-details/book-details.component.ts, WebApp/src/app/book-reviews/book-reviews.component.html, WebApp/src/app/book-reviews/book-reviews.component.scss, WebApp/src/app/genre-books/genre-books.component.html
=> UI Fix and comments display

WebApp/src/app/book-attributes/book-attributes.component.html, WebApp/src/app/book-attributes/book-attributes.component.scss, WebApp/src/app/book-details/book-details.component.scss
UI Fix for overlapping components in book details page.
=> UI Fix for overlapping components

WebApp/src/app/book-attributes/book-attributes.component.html, WebApp/src/app/book-attributes/book-attributes.component.scss, WebApp/src/app/book-attributes/book-attributes.component.ts, WebApp/src/app/book-details/book-details.component.ts, WebApp/src/app/book-reviews/book-reviews.component.html, WebApp/src/app/book-reviews/book-reviews.component.ts, WebApp/src/app/models/general-models.ts, WebApp/src/app/services/api.service.ts, WebApp/src/app/services/global.service.ts
Created dynamic data binding to reviews and ratings
=> Added dynamic reviews and dynamic rating

WebApp/cypress/integration/book-details.specs.ts, WebApp/src/app/book-details/book-details.component.html, WebApp/src/app/book-reviews/book-reviews.component.html
Created a cypress test script for testing book-details logic.
=> Cypress test for Book-Details Page

WebApp/src/app/book-attributes/book-attributes.component.html, WebApp/src/app/book-attributes/book-attributes.component.ts, WebApp/src/app/book-details/book-details.component.ts, WebApp/src/app/book-reviews/book-reviews.component.html, WebApp/src/app/book-reviews/book-reviews.component.ts, WebApp/src/app/common-menu/common-menu.component.ts, WebApp/src/app/services/global.service.ts
Data is now dynamically displayed in reviews page
=> dynamic bug fix

WebApp/src/app/book-attributes/book-attributes.component.html, WebApp/src/app/book-attributes/book-attributes.component.scss, WebApp/src/app/book-attributes/book-attributes.component.ts, WebApp/src/app/book-details/book-details.component.ts, WebApp/src/app/book-reviews/book-reviews.component.scss, WebApp/src/app/common-menu/common-menu.component.ts, WebApp/src/app/models/general-models.ts
Updated the UI to show Average Rating instead of Rating Counter from 5 to 1
=> Average Rating Update

WebApp/src/app/login/login.component.html
Created First Name and Last Name fields in Registration page
=> Created Fields In Register Page

WebApp/src/app/login/login.component.ts
Logic to register a new user to the application
=> Registration Final

WebApp/src/app/login/login.component.ts, WebApp/src/app/models/general-models.ts, WebApp/src/app/services/api.service.ts
Login Authentication Milestone
=> Login Authentication Milestone

WebApp/src/app/login/login.component.ts
=> Login Auth
